<?php

/**
 * @file
 * Contains media_skyfish.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function media_skyfish_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the media_skyfish module.
    case 'help.page.media_skyfish':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides skyfish.com integration to media module') . '</p>';
      return $output;

    default:
  }
}

function media_skyfish_update_8001() {
  /* @var $entityFieldManager Drupal\Core\Entity\EntityFieldManager */
  $entityFieldManager = Drupal::service('entity_field.manager');

  $fields = $entityFieldManager->getFieldDefinitions('user', 'user');

  if (isset($fields['field_skyfish_username'])) {
    die;
    $fields['field_MY_FIELD_NAME']->delete();

  }
}