media_skyfish.adminconfig:
  type: config_object
  mapping:
    media_skyfish_api_key:
      type: string
      label: 'Skyfish API Key'
    media_skyfish_api_secret:
      type: string
      label: 'Skyfish API Secret'
    media_skyfish_global_user:
      type: string
      label: 'Username'
    media_skyfish_global_password:
      type: string
      label: 'Password'
    media_skyfish_cache:
      type: string
      label: 'Cache time'
    media_skyfish_items_per_page:
      type: string
      label: 'Images per page'
