media_skyfish.adminconfig:
  type: config_object
  mapping:
    media_skyfish_api_key:
      type: string
      label: 'Skyfish API Key'
    media_skyfish_api_secret:
      type: string
      label: 'Skyfish API Secret'
