<?php

namespace Drupal\media_skyfish\Plugin\EntityBrowser\Widget;

use Drupal\Core\Form\FormStateInterface;
use Drupal\entity_browser\Plugin\EntityBrowser\Widget\Upload;

/**
 * Plugin implementation of the 'skyfish' widget.
 *
 * @EntityBrowserWidget(
 *   id = "skyfishwidget",
 *   label = @Translation("Skyfish"),
 *   description = "Adds Skyfish upload integration.",
 *   auto_select = FALSE
 * )
 */

class SkyfishWidget extends Upload {

  public function defaultConfiguration() {
    return [
      'upload_location' => 'public://skyfish',
    ] + parent::defaultConfiguration(); // TODO: Change the autogenerated stub
  }

  public function getForm(array &$original_form, FormStateInterface $form_state, array $additional_widget_parameters) {
    $form = parent::getForm($original_form, $form_state, $additional_widget_parameters);

    $form['upload'] = [
      '#type' => 'managed_file',
      '#title' => $this->t('Skyfish Upload Form'),
      '#title_display' => 'visible',
    ];

    return $form;
  }
}